name: 'Terraform Apply'


on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: "Select which module to deploy"
        options: 
        - module-1
        required: true

permissions: write-all

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_BILLING_ACCOUNT: ${{ secrets.BILLING_ACCOUNT }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory 
    - name: Terraform Init
      run: | 
        terraform init 
    
    - name: Terraform Plan
      id: plan 
      run: | 
        terraform plan -input=false
      continue-on-error: false
      
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    
    - name: Terraform Apply
      run: | 
        terraform apply -auto-approve -input=false
      continue-on-error: false

    # Terraform Output the API Gateway url
    - name: Application URL
      run: |
        terraform output
